USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_LayThongTinNhanVien]    Script Date: 3/31/2024 9:21:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_LayThongTinNhanVien]
@TENLOGIN NVARCHAR (50)
AS
DECLARE @TENUSER NVARCHAR(50), @UID INT
	SELECT @UID= UID, @TENUSER=NAME FROM sys.sysusers
	WHERE sid = SUSER_SID(@TENLOGIN)
	SELECT MANV = @TENUSER,
	HOTEN = (SELECT HO+ ' '+ TEN FROM NHANVIEN WHERE MANV = @TENUSER ),
	TENNHOM= NAME
	FROM sys.sysusers
	WHERE UID = (SELECT GROUPUID
	FROM SYS.SYSMEMBERS
	WHERE MEMBERUID= @UID)

GO


